# Generated by Django 5.2.7 on 2026-05-19 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='carros/', verbose_name='Imagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carros_anunciados', to=settings.AUTH_USER_MODEL, verbose_name='Anunciante')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='cars.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['-criado_em'],
            },
        ),
    ]
