# Generated by Django 5.2.7 on 2026-05-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='fonte',
            field=models.CharField(choices=[('externo', 'API Externa'), ('usuario', 'Anúncio de Usuário'), ('interno', 'Cadastro Interno')], default='externo', max_length=10),
        ),
        migrations.AddField(
            model_name='carro',
            name='id_externo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='link_origem',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
    ]
