# Generated by Django 5.2.7 on 2026-05-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('combustivel', models.CharField(blank=True, max_length=50, verbose_name='Combustível')),
                ('cambio', models.CharField(blank=True, max_length=50, verbose_name='Câmbio')),
                ('quilometragem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('fonte', models.CharField(choices=[('mercadolivre', 'Mercado Livre'), ('olx', 'OLX'), ('webmotors', 'Webmotors'), ('usuario', 'Anúncio de Usuário')], default='usuario', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='anuncios/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vendido', 'Vendido'), ('pausado', 'Pausado')], default='ativo', max_length=10)),
                ('dados_externos', models.JSONField(blank=True, default=dict, verbose_name='Dados de Scraping (JSON completo)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
