# Generated by Django 5.2.7 on 2026-05-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='anunciante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to=settings.AUTH_USER_MODEL, verbose_name='Anunciante'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.marca', verbose_name='Marca'),
        ),
    ]
