# Generated by Django 5.2.7 on 2026-05-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Portal')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL do Portal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portais',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='fonte',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='FotoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/%Y/%m/%d/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='0 = primeira foto (destaque na listagem)', verbose_name='Ordem')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='anuncios.anuncio', verbose_name='Anúncio')),
            ],
            options={
                'verbose_name': 'Foto de Anúncio',
                'verbose_name_plural': 'Fotos de Anúncio',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='portal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='anuncios.portal', verbose_name='Portal de Origem'),
            preserve_default=False,
        ),
    ]
