# Generated by Django 5.2.7 on 2026-05-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_portal_remove_anuncio_fonte_remove_anuncio_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('uf', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'estados',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='placa_preta',
            field=models.BooleanField(default=False, help_text=' Se marcado, o veiculo é de colecionador', verbose_name='placa_preta'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_ibge', models.CharField(blank=True, max_length=7, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.estado')),
            ],
            options={
                'verbose_name': 'estados',
                'ordering': ['nome'],
                'unique_together': {('nome', 'estado')},
            },
        ),
    ]
