# Generated by Django 5.2.7 on 2026-05-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_estado_anuncio_placa_preta_cidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome'], 'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nome'], 'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
    ]
