/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarroIdRouteImport } from './routes/carro.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarroIdRoute = CarroIdRouteImport.update({
  id: '/carro/$id',
  path: '/carro/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/busca': typeof BuscaRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/carro/$id': typeof CarroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/busca': typeof BuscaRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/carro/$id': typeof CarroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/busca': typeof BuscaRoute
  '/favoritos': typeof FavoritosRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/carro/$id': typeof CarroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/busca'
    | '/favoritos'
    | '/perfil'
    | '/sobre'
    | '/carro/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/busca'
    | '/favoritos'
    | '/perfil'
    | '/sobre'
    | '/carro/$id'
  id:
    | '__root__'
    | '/'
    | '/anunciar'
    | '/busca'
    | '/favoritos'
    | '/perfil'
    | '/sobre'
    | '/carro/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  BuscaRoute: typeof BuscaRoute
  FavoritosRoute: typeof FavoritosRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
  CarroIdRoute: typeof CarroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carro/$id': {
      id: '/carro/$id'
      path: '/carro/$id'
      fullPath: '/carro/$id'
      preLoaderRoute: typeof CarroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  BuscaRoute: BuscaRoute,
  FavoritosRoute: FavoritosRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
  CarroIdRoute: CarroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
